[tool.poetry]
name = "pymeter"
version = "0.1.0"
description = ""
authors = ["Kelvin.Ye <testmankelvin@163.com>"]
readme = 'README.md'

packages = [
    { include = "pymeter" },
    { include = "pymeter/**/*.py" }
]

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[tool.poetry.dependencies]
python = "^3.8"
jsonpath = "^0.82"
orjson = "^3.5.2"
sqlalchemy = "^1.3.20"
cx-Oracle = "^8.1.0"
sshtunnel = "^0.4.0"
pycryptodome = "^3.10.1"
gevent = "^21.1.2"
python-socketio = "^5.2.1"
requests="^2.25.1"
flask = "^2.0.1"
flask_socketio = "^5.0.3"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-html = "*"
flake8 = "*"
yapf = "*"
isort = "*"

[build-system]
requires = [
    "setuptools>=50.0",
    "poetry>=1.1.5"
]
build-backend = "poetry.masonry.api"

[tool.isort]
profile = "pycharm"
line_length = 120
force_single_line = true
multi_line_output = 3
