[tool.poetry]
name = "pymeter"
version = "0.1.0"
description = ""
authors = ["Kelvin.Ye <testmankelvin@163.com>"]
readme = 'README.md'

packages = [
    { include = "pymeter" },
    { include = "pymeter/**/*.py" }
]

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

# [[tool.poetry.source]]
# name = "tsinghua"
# url = "https://pypi.tuna.tsinghua.edu.cn/simple"
# default = true

[tool.poetry.dependencies]
python = "^3.8"
jsonpath = "0.82"
orjson = "3.8.1"
xmltodict = "0.13.0"
sqlalchemy = "1.4.44"
cx-Oracle = "8.3.0"
mysql-connector-python = "8.0.31"
psycopg2 = { version = "2.9.5", markers = "platform_system=='Windows' or platform_system=='Linux'"}
psycopg2-binary = { version = "2.9.5", markers = "sys_platform=='darwin'" }
pyodbc = "4.0.35"
sshtunnel = "0.4.0"
pycryptodome = "3.15.0"
gevent = "22.10.2"
python-engineio = "4.3.4"
python-socketio = "5.7.2"
requests="2.28.1"
pytypes = "1.0b10"
tabulate = "0.9.0"

[tool.poetry.dev-dependencies]
flask = "*"
pytest = "*"
pytest-html = "*"
flake8 = "*"
yapf = "*"
isort = "*"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "pycharm"
line_length = 120
force_single_line = true
multi_line_output = 3
