[tool.poetry]
name = "pymeter"
version = "0.1.0"
description = ""
authors = ["Kelvin.Ye <testmankelvin@163.com>"]
readme = 'README.md'

packages = [
    { include = "pymeter" },
    { include = "pymeter/**/*.py" }
]

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

# [[tool.poetry.source]]
# name = "tsinghua"
# url = "https://pypi.tuna.tsinghua.edu.cn/simple"
# default = true

[tool.poetry.dependencies]
python = "^3.8"
jsonpath = "0.82"
orjson = "3.6.6"
xmltodict = "0.12.0"
sqlalchemy = "1.4.30"
cx-Oracle = "8.3.0"
sshtunnel = "0.4.0"
pycryptodome = "3.14.1"
gevent = "21.12.0"
python-engineio = "4.3.1"
python-socketio = "5.5.1"
requests="2.26.0"
flask = "2.0.2"
flask-socketio = "5.1.1"
pytypes = "1.0b10"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-html = "*"
flake8 = "*"
yapf = "*"
isort = "*"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "pycharm"
line_length = 120
force_single_line = true
multi_line_output = 3
